Gráfico de distribuição etária
Arkade-Team/Arkade pull request #46
Opened 2020-10-08 12:55 UTC by fabiotk

COMO coordenador do HC
PARA visualizar a distribuição das faixas etárias
QUERO um gráfico acessível a partir da homepage que mostre a distribuição da quantidade de consultas para cada faixa etária definida

2020-10-08 13:59 UTC, jooaodanieel commented
Salve @fabiotk dei uma olhada no código e vou deixar uns comentários aqui

- o arquivo do cucumber parece que tá ok, mas ele não tá sendo chamado ao rodar os testes, acredito que seja porque tá sem a extensão `.feature` no arquivo
- a página do gráfico ficou um pouco esquisita por dois motivos:
  1. o título tá sendo encoberto pela navbar, talvez seja viável corrigir isso colocando a tag dele dentro de alguma `<div>`
  2. as barras na horizontal estão um pouco estranhas, será que rola colocar as idades no eixo x e a contagem no eixo y?

![Screenshot_20201008_105455](https://user-images.githubusercontent.com/12701604/95468763-39b58680-0955-11eb-8be9-dc96f641ca63.png)

2020-10-08 18:42 UTC, fabiotk commented
@jooaodanieel fiz algumas alterações, porém não sei se o gráfico é o correto/melhor opção a ser utilizado.

2020-10-08 22:30 UTC, jooaodanieel commented on app/views/appointment/index.html.erb
> +    <%= column_chart Appointment.group(:age).count, title: "Distribuição das idades" %>
Experimenta uma estrutura como essa daqui:

```erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col">
        <%= column_chart Appointment.group(:age).count, title: "Distribuição das idades" %>
      </div>
    </div>
  </div>
</div>
```

2020-10-08 22:31 UTC, jooaodanieel requested changes
Deixei apenas um comentário na view

2020-10-08 22:31 UTC, jooaodanieel commented on app/views/appointment/index.html.erb
> +    <%= column_chart Appointment.group(:age).count, title: "Distribuição das idades" %>
Experimenta uma estrutura dessa:

```erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col">
        <%= column_chart Appointment.group(:age).count, title: "Distribuição das idades" %>
      </div>
    </div>
  </div>
</div>

```

2020-10-08 23:28 UTC, fabiotk commented on app/views/appointment/index.html.erb
> +    <%= column_chart Appointment.group(:age).count, title: "Distribuição das idades" %>
estrutura inserida

2020-10-09 02:24 UTC, jooaodanieel approved these changes

2020-10-10 20:11 UTC, merged