Geraçao do grafico de Consultas por Gênero de acordo com o período selecionado
Arkade-Team/Arkade pull request #63
Opened 2020-11-04 21:04 UTC by gustavomolina17

2020-11-04 21:07 UTC, gustavomolina17 commented
Geração do gráfico de acordo com o período de dias selecionados. Simultaneamente ocorre a atualização da tabela de Total de Consultas por período.

2020-11-05 17:35 UTC, pedr0hug0 commented on app/views/appointment/index.html.erb
> +div class="jumbotron">
quebrou a chave do div do jumbotron.

2020-11-05 17:37 UTC, pedr0hug0 requested changes

2020-11-05 17:37 UTC, pedr0hug0 commented on app/views/appointment/index.html.erb
> +div class="jumbotron">
quebrou a chave do div do jumbotron.

2020-11-05 17:48 UTC, pedr0hug0 commented on app/views/appointment/index.html.erb
> +div class="jumbotron">
1 dia significa hoje e ontem ou apenas hoje?
Verificar com o time.

2020-11-05 17:48 UTC, gustavomolina17 commented on app/views/appointment/index.html.erb
> +div class="jumbotron">
![Screenshot from 2020-11-05 14-48-09](https://user-images.githubusercontent.com/70485830/98277333-037c1e80-1f76-11eb-9c83-7a871e84dee9.png)

2020-11-05 17:49 UTC, gustavomolina17 commented on app/views/appointment/index.html.erb
> +div class="jumbotron">
Está certo aqui as chaves conforme o print acima mostra.

2020-11-05 18:02 UTC, gustavomolina17 commented on app/views/appointment/index.html.erb
> +div class="jumbotron">
@pedr0hug0  desculpe erro meu vou subir o arquivo arrumado

2020-11-05 18:15 UTC, pedr0hug0 approved these changes

2020-11-05 19:04 UTC, pedr0hug0 requested changes

2020-11-05 19:04 UTC, pedr0hug0 commented on app/views/appointment/index.html.erb
> +            <%= number_field_tag :days, params[:days], placeholder: "Selecione a quantidade de dias", min: 1, class:"form-control" %>
Min: 0 para buscar apenas do dia.

2020-11-05 19:11 UTC, gustavomolina17 commented on app/views/appointment/index.html.erb
> +            <%= number_field_tag :days, params[:days], placeholder: "Selecione a quantidade de dias", min: 1, class:"form-control" %>
@pedr0hug0 isso resolve a questão, porém logicamente não faz sentido uma vez que ninguém busca pelo período de 0 dias. Irei trabalhar em outra solução.

2020-11-06 13:08 UTC, gustavomolina17 commented on app/views/appointment/index.html.erb
> +            <%= number_field_tag :days, params[:days], placeholder: "Selecione a quantidade de dias", min: 1, class:"form-control" %>
@pedr0hug0 Subi já as modificações. Favor fazer a validação.

2020-11-06 14:17 UTC, jooaodanieel commented
@Gustavo171991 tinha escalonado o PR do Pedro para dar merge. Vou dar merge no seu aqui assim que o CI passar na master, ok?

2020-11-06 17:20 UTC, pedr0hug0 approved these changes

2020-11-06 17:29 UTC, merged